# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing
VAGRANTFILE_API_VERSION = '2'

PM_ROOT = File.dirname(__FILE__)

box_url = "http://downloads.mesosphere.io/playa-mesos/playa_mesos_ubuntu_14.04-virtualbox.box"


# #############################################################################
# Vagrant VM Definitions
# #############################################################################


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :private_network, ip: "10.141.141.10"

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  config.ssh.forward_agent = true

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "playa_mesos_ubuntu_14.04"

  # Hardcoded the Playa Mesos box
  config.vm.box_url = box_url

  # Only VirtualBox provider
  config.vm.provider :virtualbox do |vb|
    vb.name = "elsa"
    vb.customize ['modifyvm', :id, '--memory', "2048"]
    vb.customize ['modifyvm', :id, '--cpus',   "2"]
  end

  # Make the project root available to the guest VM.
  # config.vm.synced_folder '.', '/vagrant'

  # Provision the ElSA app
  config.vm.provision :shell do |shell|
    shell.path = 'provision_elsa.sh'
  end

end
